#!/usr/bin/env node

var exec = require('child_process').exec;
console.log('Installing...')
var child = exec('cd ' + __dirname + '; sudo apt-get install -y npm; sudo npm install --no-bin-links;')
child.stdout.on('data', function(data) {
  console.log(data)
})
child.stderr.on('data', function(data) {
  console.log(data)
})
